### ISSUE TITLE
Should the macro __riscv_c and __riscv_compressed defined for Zca?

### ISSUE THREAD

**Issue by KaiYG** [riscv-non-isa/riscv-c-api-doc#51]
Should the macro `__riscv_c` (and `__riscv_compressed`) defined when only Zca is enabled?
Also, seems GCC and Clang behave differently in this case, e.g., for `-march=rv32i_zca`,
GCC: undefined `__riscv_c`, while defined `__riscv_compressed`
LLVM: undefined both.

**Comment by cmuellner** [comment]
Related questions:
* https://github.com/riscv-non-isa/riscv-asm-manual/issues/91
* https://github.com/riscv/riscv-isa-manual/pull/1121

**Comment by kito-cheng** [comment]
`__riscv_compressed` was deprecated, but I guess we should consider redefine that as defined if any extension provided compressed instruction is available? We have `C` and `Zca` now, but not guarantee we won't have more independent `Zc*` extensions .

cc @a4lg

**Comment by KaiYG** [comment]
As the Zc spec v1.0.4-2 added the rule that C implies Zca, I think existence of the compressed instructions can be reported by `__riscv_zca` now.

**Comment by cmuellner** [comment]
Thanks for the update and closing the ticket!
