### ISSUE TITLE
Why were the __riscv_m, ... macros deprecated, will there be an alternative?

### ISSUE THREAD

**Issue by camel-cdr** [riscv-non-isa/riscv-c-api-doc#71]
I'd like to select between different instructions depending on the extensions enabled by the compiler.
This would've worked using the `__riscv_m`, ... macros, but they were deprecated.
Are there plans to allow compiletime extension discovery, or is this already a thing and I just missed something?

**Comment by topperc** [comment]
They weren't deprecated. They were removed from the table because the table wasn't updated as each new extension was ratified. There is now a generic section https://github.com/riscv-non-isa/riscv-c-api-doc/blob/master/riscv-c-api.md#architecture-extension-test-macros

**Comment by camel-cdr** [comment]
Ah, thanks a lot.
