### ISSUE TITLE
Change branch from "master" to "main"

### ISSUE THREAD

**Issue by kersten1** [riscv-non-isa/riscv-c-api-doc#77]
As a gentle reminder, the "Friendly Terminology" policy [link](https://docs.google.com/document/d/1lmEMU_Gi1KRQB2PtbjUSgbtlx5frUK40AuMO1OICSEY/) which uses the "Inclusive Naming" community [link](https://inclusivenaming.org/) includes the word "master" as a [Tier 1: Replace Immediately](https://inclusivenaming.org/word-lists/tier-1/) word.

You can follow these steps to rename your branch: https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab

**Comment by kito-cheng** [comment]
I created [main](https://github.com/riscv-non-isa/riscv-c-api-doc/tree/main) branch, but seems like I don't have enough permission to change the default branch... @cmuellner @jjscheel need your help here

**Comment by cmuellner** [comment]
> I created [main](https://github.com/riscv-non-isa/riscv-c-api-doc/tree/main) branch, but seems like I don't have enough permission to change the default branch... @cmuellner @jjscheel need your help here

Thanks for driving this!

I can simply use the GitHub interface to rename the branch to `main`.
This also takes care of the following:
* update 9 pull requests targeting this branch across 4 repositories
* update 1 branch protection rule that explicitly targets master

But to do that, I need to delete the `main` branch that you have just created.

**Comment by cmuellner** [comment]
Deleted the `main` branch and renamed `master` to `main`.

Closing, as completed.
